Update info screen
TehShrike/memorize-text-app pull request #25
Opened 2019-03-01 17:31 UTC by Elisarmor

Fixes #21

2019-03-06 17:01 UTC, TehShrike requested changes
w00t

2019-03-06 17:01 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +					There are no sheets in this workbook.
This seems redundant given the "This workbook has 0 sheets" message above.  I think we can just delete this case and have `if workbook.sheets.length === 1` + `elseif workbook.sheets.length > 1` cases.

2019-03-06 17:01 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +					{#each workbook.sheets as sheet}
instead of relying on `lastSheetId`, we can use the current sheet index using the [`#each` block](https://svelte.technology/guide#each-blocks) syntax:

```
{#each workbook.sheets as sheet, index}
```

2019-03-06 17:01 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +							<a href="{ asr.makePath('workbook.sheet.memorize', { key, sheetId: sheet.id }) }">{sheet.name}</a> ,&nbsp;
The repetition of the link makes me nervous - I think the link should be the same for every line, with only the period/comma/"and" varying:

```
<a href="{ asr.makePath('workbook.sheet.memorize', { key, sheetId: sheet.id }) }">{sheet.name}</a>{#if index === workbook.sheets.length - 1}.{#elseif index === workbook.sheets.length - 2}, and {else}, {/if}
```
...but it's kind of awkward to cram them all on the end of that line there, so It seems preferable to make a computed property that returns a helper function that could be called:

```
computed: {
	sheetSentenceSeparator: workbook => index => {
		if (index === workbook.sheets.length - 1) {
			return '.'
		} else if (index === workbook.sheets.length - 2) {
			return ', and '
		}

		return ', '
	}
}
```
allowing
```
<a href="{ asr.makePath('workbook.sheet.memorize', { key, sheetId: sheet.id }) }">{sheet.name}</a>{sheetSentenceSeparator(index)}
```

2019-03-06 17:01 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +				<a href="https://docs.google.com/spreadsheets/d/{key}" target="_blank">View workbook on Google Sheets</a>
We should set [`rel`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) to `noopener` and `external`, too.

2019-03-06 17:01 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +			logWorkbook(workbook) {
This can be removed 🐳

2019-03-25 22:36 UTC, Vehmloewff commented
Ready to review again!

2019-03-28 02:35 UTC, Vehmloewff commented
Ready for review.

2019-07-04 12:41 UTC, TehShrike commented on client/view/workbook/info/Info.html
> +			}
```suggestion
		}
```

2019-07-04 13:06 UTC, merged